export const foodMenu = [
    {
      id: 1,
      name: 'Margherita Pizza',
      description: 'Classic pizza with tomato, mozzarella, and basil.',
      price: 9.99,
      image: 'https://as1.ftcdn.net/v2/jpg/06/08/19/46/1000_F_608194671_BNXAs98uEbTi1OXYHSN3GiVtJPbTIom6.jpg',
    },
    {
      id: 2,
      name: 'Chicken Alfredo Pasta',
      description: 'Creamy Alfredo sauce with grilled chicken and fettuccine.',
      price: 12.99,
      image: 'https://www.michelinas.com/wp-content/uploads/2017/09/10521_FetAlfChicBro-1024x478.png',
    },
    {
      id: 3,
      name: 'Caesar Salad',
      description: 'Fresh romaine lettuce, croutons, parmesan, and Caesar dressing.',
      price: 7.99,
      image: 'https://media.istockphoto.com/id/1152496623/photo/fresh-caesar-salad-isolated-on-a-white-background.jpg?s=612x612&w=0&k=20&c=3MyF6hp_JZCpi2YJDENTPtQt1ZJ12Zrk2V5ZoNUco-I=',
    },
    {
      id: 4,
      name: 'Burger Deluxe',
      description: 'Beef patty with lettuce, tomato, cheese, and special sauce.',
      price: 8.99,
      image: 'https://www.pngkey.com/png/detail/244-2446319_chicken-grill-deluxe-burger-a-w-grilled-chicken.png',
    },
    {
      id: 5,
      name: 'Vegetarian Sushi Roll',
      description: 'Avocado, cucumber, and carrot wrapped in seaweed and rice.',
      price: 10.99,
      image: 'https://www.pngitem.com/pimgs/m/244-2447207_veg-sushi-png-transparent-png.png',
    },
    {
      id: 6,
      name: 'Chocolate Brownie Sundae',
      description: 'Warm chocolate brownie topped with vanilla ice cream and chocolate sauce.',
      price: 6.99,
      image: 'https://static.vecteezy.com/system/resources/previews/025/229/429/original/tasty-brownies-ice-cream-isolated-on-transparent-background-png.png',
    },
    {
      id: 7,
      name: 'Spaghetti Bolognese',
      description: 'Spaghetti with meat sauce, tomatoes, and herbs.',
      price: 11.99,
      image: 'https://static.vecteezy.com/system/resources/previews/025/076/480/non_2x/home-made-spaghetti-bolognese-made-with-meat-and-pasta-isolated-illustration-ai-generative-png.png',
    },
    {
      id: 8,
      name: 'Grilled Salmon',
      description: 'Freshly grilled salmon with lemon and herbs.',
      price: 14.99,
      image: 'https://static.vecteezy.com/system/resources/previews/026/853/371/original/grilled-salmon-steak-isolated-on-transparent-background-created-with-generative-ai-png.png',
    },
    {
      id: 9,
      name: 'Mango Tango Smoothie',
      description: 'Refreshing smoothie with mango, banana, and yogurt.',
      price: 4.99,
      image: 'https://static.vecteezy.com/system/resources/thumbnails/021/121/847/small/mango-smoothie-mango-drink-menu-watercolor-png.png',
    },
    {
      id: 10,
      name: 'Caprese Salad',
      description: 'Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze.',
      price: 8.49,
      image: 'https://static.vecteezy.com/system/resources/previews/021/509/077/original/white-plate-with-caprese-salad-isolated-on-a-transparent-background-png.png',
    },
    {
      id: 11,
      name: 'BBQ Chicken Wings',
      description: 'Crispy chicken wings glazed with barbecue sauce.',
      price: 9.49,
      image: 'https://static.vecteezy.com/system/resources/previews/024/499/883/original/bbq-chicken-wings-free-generative-ai-free-png.png',
    },
    {
      id: 12,
      name: 'Vegetable Stir-Fry',
      description: 'Assorted vegetables stir-fried in a savory sauce.',
      price: 10.99,
      image: 'https://d3gg7p8kl1yfy0.cloudfront.net/orangechxstirfry_detail_1_2022.jpg',
    },
    {
      id: 13,
      name: 'Fruit Salad Bowl',
      description: 'A colorful mix of fresh fruits served in a bowl.',
      price: 5.99,
      image: 'https://static.vecteezy.com/system/resources/previews/025/229/654/original/tasty-fruit-salad-bowl-isolated-on-transparent-background-png.png',
    },
    {
      id: 14,
      name: 'Cheese Platter',
      description: 'Assorted cheeses, crackers, and grapes.',
      price: 13.99,
      image: 'https://assets.stickpng.com/images/5af16e356554160a79bea008.png',
    },
    {
      id: 15,
      name: 'Vanilla Bean Cheesecake',
      description: 'Creamy cheesecake with a hint of vanilla.',
      price: 7.49,
      image: 'https://img.taste.com.au/IJmBOz26/taste/2016/11/classic-no-bake-vanilla-cheesecake-88473-1.jpeg',
    },
    {
      id: 16,
      name: 'Shrimp Scampi',
      description: 'Shrimp sautéed in garlic and white wine sauce, served over pasta.',
      price: 16.99,
      image: 'https://png.pngtree.com/png-vector/20231017/ourlarge/pngtree-shrimp-with-pasta-haute-cuisine-png-image_10200357.png',
    },
    {
      id: 17,
      name: 'Chicken Caesar Wrap',
      description: 'Grilled chicken, romaine lettuce, and Caesar dressing in a wrap.',
      price: 9.99,
      image: 'https://olo-images-live.imgix.net/8a/8a4acbd40552420abbc2d0449d89723c.jpg?auto=format%2Ccompress&q=60&cs=tinysrgb&w=1725&h=975&fit=fill&fm=png32&bg=transparent&s=a0a8c242b74068d6358cf484a7c7ea31',
    },
    {
      id: 18,
      name: 'Teriyaki Chicken Bowl',
      description: 'Teriyaki-glazed chicken with vegetables and rice.',
      price: 12.49,
      image: 'https://previews.123rf.com/images/wuttichok/wuttichok1107/wuttichok110700199/10040537-rice-with-chicken-teriyaki-on-white-background.jpg',
    },
    {
      id: 19,
      name: 'Classic Tiramisu',
      description: 'Italian dessert with layers of coffee-soaked ladyfingers & mascarpone.',
      price: 8.99,
      image: 'https://img.freepik.com/premium-photo/classic-italian-tiramisu-cake-isolated-white-background-generative-ai_971989-565.jpg',
    },
    {
      id: 20,
      name: 'Avocado Toast',
      description: 'Sliced avocado on toasted bread with toppings.',
      price: 6.49,
      image: 'https://i.pinimg.com/originals/a6/d9/a2/a6d9a221bbbcfc291df72d79dd0eac0a.jpg',
    },
  ];
  
  
  